module.exports = {
  USER_CONNECT: "USER_CONNECT",
  OFFER_REQUEST_CREATED: "OFFER_REQUEST_CREATED",
  OFFER_CREATED: "OFFER_CREATED",
  OFFER_ACCEPTED: "OFFER_ACCEPTED",
  OFFER_UPDATED: "OFFER_UPDATED",
  END_CAMPAIGN: "END_CAMPAIGN",
  REQUEST_OUT_THE_DOOR_PRICE: "REQUEST_OUT_THE_DOOR_PRICE",
  MARK_AS_READ: "MARK_AS_READ",
  GET_LAST_SEEN_LIST: "GET_LAST_SEEN_LIST",
  SET_LAST_SEEN: "SET_LAST_SEEN",
  MESSAGE_SEND: "MESSAGE_SEND",
  ADD_MEMBER_REQUEST: "ADD_MEMBER_REQUEST",
};
